version: '3'

services:

  orchestrator:
    build:
      context: .
      dockerfile: ./Orchestrator/Dockerfile
    environment:
      ORCHESTRATOR_HTTP_PORT: 8080
      ORCHESTRATOR_TCP_PORT: 7777
      ORCHESTRATOR_DB: db_orchesterator
      ORCHESTRATOR_DB_NAME: orchestrator
      ORCHESTRATOR_DB_PORT: 5432
      ORCHESTRATOR_DB_USER: postgres
      ORCHESTRATOR_DB__PASSWORD: postgres
    ports:
      - "8080:8080"
    container_name: orchesterator
    networks:
      - orchesterator
  agent:
    build:
      context: .
      dockerfile: ./Agent/Dockerfile
    environment:
      HOST: orchesterator
      PORT: 7777
      MAX_GOROUTINES_AGENT: 2
    deploy:
      replicas: 1
    networks:
      - orchesterator
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_orchesterator
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - orchesterator


networks:
  orchesterator: